#!/bin/bash

# Counter variable to keep track of the number of times the loop has run
counter=0

# While loop that continues until the counter reaches 10
while [ $counter -lt 10 ]
do
  echo "Best School"
  counter=$((counter+1))
done
