#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.

hours=0
minutes=0

while [ $hours -lt 13 ]; do
  while [ $minutes -lt 60 ]; do
    echo "$hours:$minutes"
    minutes=$((minutes + 1))
  done
  minutes=0
  hours=$((hours + 1))
done | head -70
