#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

hours=0
minutes=0

while [ $hours -lt 13 ]; do
  echo "Hour: $hours"
  while [ $minutes -lt 60 ]; do
    echo "$minutes"
    minutes=$((minutes + 1))
  done
  minutes=0
  hours=$((hours + 1))
done
