#!/usr/bin/env bash
# This script displays the content of the cueernt directory in list format

for file in *
do
  if [[ $file != .* ]]
  then
    name=$(echo $file | cut -d'-' -f2-)
    echo " - $name"
  fi
done
