#!/usr/bin/env bash
#This is a script that stops 4-to_infinity_and_beyond process
# You must use kill

# Terminate  the infinnate process 
id=$(pgrep "bash ./4-to_infinity_and_beyond -f)

# Terminate if[-n "$id"];then
  kill -15 "$id"
fi
